apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    codefresh.io/entity: internal-config
    codefresh.io/internal: "true"
  name: in-cluster
spec:
  destination:
    namespace: bla33
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      include: '{all-runtimes-all-clusters/*.yaml,all-runtimes-all-clusters/**/*.yaml,runtimes/bla33/*.yaml,runtimes/bla33/**/*.yaml,control-planes/*.yaml,control-planes/**/*.yaml}'
      recurse: true
    path: resources
    repoURL: https://github.com/danielm-codefresh/suggested-isc-bla.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
    - allowEmpty=true
